import React from "react";
const data={
    "Rhea":'Rhea Singha is the reigning Miss Universe India 2024, a celebrated model and beauty pageant titleholder. She has represented India on prestigious global platforms, including Miss Teen Universe 2023 in Madrid, where she secured a spot in the Top 6, and made history as the first Indian to win the Miss Teen Earth title. Beyond her achievements in pageantry, Rhea is a fitness enthusiast and a passionate advocate for youth empowerment. She is now expanding her creative reach, connecting with audiences through engaging and motivational storytelling, and leaving a lasting impact in the world of pageantry, inspiration, and personal growth.',
    "Lima":'Dr. Lima Das is a spectacular actress who debuted in a lead role in the critically acclaimed Assamese feature film Aamis. She was honoured with the Best Actress Award at the Singapore South Asian International Film Festival and the Assam State Awards in 2019 for her outstanding performance in the film. She also acted in the National Award Winning Assamese film Emuthi Puthi as a character role. A well-known vocalist with a Bachelor of Music degree from Bhatkhande Sangeet Vidyapeeth, Lucknow, she is actively reviving old Assamese songs composed by Assam legends. She is also a great classical dancer, specialising in Odissi and Sattriya forms. She originally was a dental surgeon who served as a faculty member at the Regional Dental College, Guwahati, with 15 years of experience. Currently, she has dedicated herself to acting and creative pursuits. ',
    "Riten":"Riten Debnath, the CEO and the man behind the creation of an extraordinarily innovative online platform, Fueler, that helps creative minds showcase their impressive portfolios. Through a proof-of-work approach, the platform enables companies to evaluate candidates through real-world tasks that reflect their skills and capabilities. Hailing from Agartala, his expertise in computer tech and product consultation, has fuelled his ambition and he is on his way to creating a “non-coding” GitHub. Already a huge hit with about 50,000 individuals in the community, his product is nothing but a game-changer for job seekers who are eager to showcase their skills in today’s cut-throat competitive environment.",
    "Vijaya":"Vijaya Aswani is the visionary behind Spreefirit, with over a decade of expertise in illustration. Her work celebrates inclusive narratives and cultural richness, creating characters that move beyond conventional, template-like styles. From collaborations to curating immersive art events, Vijaya’s projects blend fun with artistic growth. A standout moment in her journey is sketching strangers on the vibrant streets of Bangalore, capturing people’s essence. Whether collaborating with brands or teaching the art of drawing, Vijaya remains committed to encouraging fearless creativity and spreading joy through her works.",
    "Bipul": "Professor Bipul Bhuyan is a passionate experimental particle physicist and a dedicated Professor of Physics at IIT Guwahati. For over two decades, he has been at the forefront of global research, exploring the fundamental mysteries of the universe. From studying matter-antimatter asymmetry to uncovering the secrets of neutrinos, his work spans prestigious international collaborations like Belle II in Japan and NOvA & DUNE in the USA. With 700+ research publications and the Best Thesis Award from Brookhaven National Laboratory, he continues to push the boundaries of modern physics. As the lead of DUNE-India, he represents India in one of the world's most ambitious neutrino experiments",
    "Sneha":"Hailing from the student fraternity of IIT Guwahati, Sneha Roy is a poet, dreamer, researcher and speaker who is currently pursuing her PhD in Gender and Literature at the Department of Humanities and Social Sciences. Her works, including poetry, have been published by Feminism in India, Muse India, Delhi Poetry Slam, Red River Press, Indie Blue Publishing (USA) and Bangalore Poetry Circle among others. She aims to foster the bridge between creative and critical arc. She has been a recipient of the Zubaan-Sasakawa Peace Foundation Grants for Young Researchers in the North-East 2021 and has won laurels at the Great Britain Debate 2018, and the Wingword Poetry Prize organised by Delhi Poetry Slam in 2016.",
    "Rajni":'Rajni Basumatary is a scriptwriter, director, actor and producer. Hailing from Assam, she strongly believes that culture and creativity can engender social change in communities. She debuted as a director in 2014 with "Raag, the Rhythm of Love", and her 2019 film, “Jwlwi - The Seed” won her several awards such as the Assam State Film Awards for Best Actor (Female), Best Film in Other Language category and Best Film in other than Assamese language from Prag Cine Awards among many others. She has acted in a few highly successful and acclaimed films, including Mary Kom (2014) and the Netflix series "Rana Naidu” (2023). Her third directorial film, "WILD SWANS" (Gorai Phakhri) had its World Premiere at Vancouver International Film Festival ’23.',
    "Shankuraj":"Shankuraj Konwar, a singer-songwriter, composer and producer from Jorhat, Assam, has redefined Assamese music with his soulful creations. Known for hits like Joloprapat and Alakananda, his compositions blend captivating lyrics with mesmerizing melodies. With 151K+ subscribers and 20M+ views on YouTube, Shankuraj’s artistry symbolizes a new era of music, inspiring listeners and evoking deep emotions."
}
export default data;